CREATE DATABASE IF NOT EXISTS `monkey`;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `monkey`.`login` (
  `user_id` INT(12) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(65535) NOT NULL,
  `password` VARCHAR(65535) NOT NULL,
  `salt1` TEXT NOT NULL,
  `salt2` TEXT NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `monkey`.`forms` ( 
  `form_id` INT(12) NOT NULL AUTO_INCREMENT,
  `creator_username` VARCHAR(65535) NOT NULL,
  `title` VARCHAR(65535) NOT NULL,
  `description` VARCHAR(65535) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modified_date` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TEXT NOT NULL,
  `form_url` TEXT NOT NULL,
  `response_count` INT NOT NULL,
  PRIMARY KEY (`form_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;